$(document).ready(function() {
    new TypeIt('.type-it', {
        speed: 90,
        lifeLike: false,
        autoStart: false,
        startDelay: 2200
    })
    .type('Hi, my name&#8217;s Zack.')
    .pause(800)
    .break()
    .pause(200)
    .break()
    .type('I&#8217;m a digital designer from Boston who cares about ')
    .pause(2000)
    .type('simplicity.')
    .pause(1000)
    .delete(11)
    .pause(300)
    .type('usability.')
    .pause(1000)
    .delete(10)
    .pause(300)
    .type('empathy.')
    .pause(1000)
    .delete(8)
    .pause(300)
    .type('collaboration.')
    .pause(1000)
    .delete(14)
    .pause(300)
    .type('craft.')
    .pause(1000)
    .delete(6)
    .pause(300)
    .type('creativity.')
    .pause(1000)
    .delete(11)
    .pause(300)
    .type('technology.')
    .pause(1000)
    .delete(11)
    .pause(300)
    .type('transparency.')
    .pause(1000)
    .delete(13)
    .pause(300)
    .type('strong coffee.')
    .pause(1000)
    .delete(14)
    .pause(300)
    .type('<strong>breakfast cereal</strong>.')
    .pause(1000)
    .delete(17)
    .pause(900)
    .type('<span>Cinnamon Toast Crunch</span>.')
    ;


});
